### ISSUE TITLE
Service & Repository 1:1 관계 후 Service 간 참조 o VS Service & Repository 1:N 관계 후 Service 간 참조 x

### ISSUE THREAD

**Issue by gimseonjin** [gimseonjin/hanghae99-5#1]
Service 계층은 Repository에서 가져온 데이터 즉 DB에서 가져온 데이터를 Transaction 관리 및 무결성, 예외 처리 등을 담당합니다.

그런데 만약 타 Service에서 도메인을 사용하고 싶은 경우, 예를 들어 OrderService에서 Restaurant 엔티티를 가져오고 싶은 경우, OrderService는 

Restaurant Serivce에서 구현된 getRestaurant를 사용해야하는지, 아니면 Restaurant Repository를 통해 findById 등으로 가져와야 하는 지 궁금합니다.

저는 Service간의 참조가 생길 경우, 자칫 잘못하면 순환참조가 생길 수 있기 때문에 하위 계층을 참조해야 한다고 생각합니다.

예를 들어 
-Controller는 Service와 Repository 참조를 가질 수 있다(Controller x)
-Service는 Repository 참조를 가질 수 있다.(Controller x Service x)
-Repository는 Domain 참조를 가질 수 있다.(Controller x Service x Repository x)

**Comment by 9sanha** [comment]
말씀하신 대로 같은 계층간 참조는 지양되고 있습니다. 스프링에서는 이를 막아주는 것으로 알고있어요. 떄문에 후자의 방법을 사용하시는 것이 맞습니다!
