### ISSUE TITLE
dto to model 로직은 어디에 구현되어야 하는가?? model vs service

### ISSUE THREAD

**Issue by gimseonjin** [gimseonjin/hanghae99-5#2]
dto 는 model이 다른 서비스에 공개 되지 않고 원하는 정보만 보여주기 위해 사용된다.

그래서 값을 받아오거나 값을 반환할 때 이를 사용한다.

이전까지는 dto to model 변환을 dto 엔티티에서 toModel을 사용하는 방식으로 사용했다.

그러나 이번 과제에서는 dto를 모델로 변환하기 위해서는 repository에서 값을 받아와야 하는 로직이 있었다.

그렇다면 service 계층에서 repository의 값을 받아와서 dto를 만들어야 한다.

이때 드는 의문은 어떤 dto는 서비스 계층에서 변환하고 어떤 dto는 dto에서 변환하는 것이 옳은 것인가 이다.

예를 들어 CreateOrderRequestDto의 경우, repository에서 값을 가져와야하기 때문에 OrderCreateService에서 dto 변환을 한다.

그 외 dto의 경우, 내부의 toModel 로직을 사용하여 변환한다.

이렇게 구현할 경우 차후 유지보수할 때, 헷갈릴 거 같기 때문에 두 위치를 일치시켜 모두 service 계층에서 변환하고 싶다.

하지만 그렇게 하면 공통의 dto를 사용할 경우, 코드 중복이 생긴다.

이럴 경우에는 어떤 것이 베스트 인가??

**Comment by 9sanha** [comment]
사실 글이 잘 이해되지 않습니다. cotroller - service 사이의 데이터 이동에는 dto를 사용하는 것이 적합하지만 service - repository 애서는 적합하지 않습니다. (역할의 차이)
정답이 정해져있지 않은 부분이니 상황에 따라 개발하시는게 베스트입니다!

https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/
dto 사용 범위에 대해 다룬 글인데 읽어보시면 좋을 것 같아요.
